# =============================================
# ACTUATOR (Pour voir les routes)
# =============================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

# ===============================
# Logging
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.esprit=DEBUG