# ===============================
# Application Name
# ===============================
spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888

# ===============================
# Server Port

server.port=8070

# ===============================
# Eureka Configuration
# ===============================
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


# chantier service
spring.cloud.gateway.routes[0].id=service-gestion-chantier
spring.cloud.gateway.routes[0].uri=lb://service-gestion-chantier
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/chantiers/**

# user service
spring.cloud.gateway.routes[1].id=service-gestion-user
spring.cloud.gateway.routes[1].uri=lb://service-gestion-user
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# projet service
spring.cloud.gateway.routes[2].id=service-gestion-projet
spring.cloud.gateway.routes[2].uri=lb://service-gestion-projet
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/projets/**



spring.cloud.gateway.routes[8].id=service-fournisseurs
spring.cloud.gateway.routes[8].uri=lb://service-fournisseurs
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/fournisseurs/**




spring.cloud.gateway.routes[3].id=notification
spring.cloud.gateway.routes[3].uri=lb://notification
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.routes[4].id=planing-taskassigne
spring.cloud.gateway.routes[4].uri=lb://planing
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/taskassigne/**

spring.cloud.gateway.routes[5].id=planing-task
spring.cloud.gateway.routes[5].uri=lb://planing
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/task/**

spring.cloud.gateway.routes[6].id=planing-project
spring.cloud.gateway.routes[6].uri=lb://planing
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/project/**

spring.cloud.gateway.routes[7].id=planing-resource
spring.cloud.gateway.routes[7].uri=lb://planing
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/resource/**

# =============================================
# ACTUATOR (Pour voir les routes)
# =============================================

spring.cloud.gateway.routes[8].id=service-materiau
spring.cloud.gateway.routes[8].uri=lb://service-materiau
spring.cloud.gateway.routes[8].predicates[0]=Path=/materiaux/**


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator

# ===============================
# Logging
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.esprit=DEBUG