# Template file for a microservice configuration in Config Server.
# Copy and rename to: <spring.application.name>.properties
# Example: service-materiau.properties

# server.port=8080
# spring.datasource.url=jdbc:mysql://localhost:3306/db
# spring.datasource.username=root
# spring.datasource.password=secret
