
# Application Name (used for Eureka registration)
spring.application.name=service-gestion-user
spring.config.import=optional:configserver:http://localhost:8888

# Server Port
server.port=8082


spring.datasource.url=${SERVICE_USER_DB_URL:jdbc:postgresql://localhost:5433/smartsite}
spring.datasource.username=${SERVICE_USER_DB_USERNAME:smartsite}
spring.datasource.password=${SERVICE_USER_DB_PASSWORD:smartsite}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8080}
keycloak.realm=${KEYCLOAK_REALM:smartsite}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:master}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}


eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

    
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.logstash.host=${LOGGING_LOGSTASH_HOST:localhost}
logging.logstash.port=${LOGGING_LOGSTASH_PORT:5000}
