spring.application.name=config-server
server.port=8888

# Native profile reads configuration files from classpath/local folders.
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config-repo

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always
